name: mjswensen.com
domain: https://mjswensen.com
permalink: /:categories/:title/
exclude: 
  - _styles
  - node_modules
  - .git
  - .gitignore
  - package.json
  - README.md
  - .sass-cache
  - cibuild.bash
  - vendor
  - build.bash
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - now.json
include:
  - .well-known
  - _redirects
